[package]
name = "hub"
version = "0.1.0"
authors = ["Max Payne <forgge@gmail.com>"]
edition = "2018"

[dependencies]
paho-mqtt = "0.6.0"
clap = "2.33.0"
nom = "5"
typenum = "1.11.2"
num = "0.2.0"
text_io = "0.1.7"
